package vim;

import java.lang.reflect.Array;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.util.Arrays;
import java.util.Comparator;

import jnr.ffi.LibraryLoader;
import jnr.ffi.mapper.DataConverter;
import jnr.ffi.mapper.FromNativeContext;
import jnr.ffi.mapper.ToNativeContext;
import jnr.ffi.Memory;
import jnr.ffi.NativeType;
import jnr.ffi.Pointer;
import jnr.ffi.StructLayout;
import jnr.ffi.Variable;
import jnr.ffi.types.*;

import static vim.VimA.*;
import static vim.VimB.*;
import static vim.VimC.*;
import static vim.VimD.*;
import static vim.VimE.*;
import static vim.VimF.*;
import static vim.VimG.*;
import static vim.VimH.*;
import static vim.VimI.*;
import static vim.VimJ.*;
import static vim.VimK.*;
import static vim.VimL.*;
import static vim.VimM.*;
import static vim.VimN.*;
import static vim.VimO.*;
import static vim.VimP.*;
import static vim.VimQ.*;
import static vim.VimR.*;
import static vim.VimS.*;
import static vim.VimT.*;
import static vim.VimU.*;
import static vim.VimV.*;
import static vim.VimW.*;
import static vim.VimX.*;
import static vim.VimY.*;

/*
 * Supported Types
 * ------
 *
 * All java primitives are mapped simply to the equivalent C types.
 *
 * - byte - 8 bit signed integer
 * - short - 16 bit signed integer
 * - int - 32 bit signed integer
 * - long - natural long (i.e. 32 bits wide on 32 bit systems, 64 bit wide on 64 bit systems)
 * - float - 32 bit float
 * - double - 64 bit float
 *
 * The width and/or signed-ness of these basic types can be specified using one of the type alias annotations.
 *  e.g.
 *
 *     // Use the correct width for the result from getpid(3)
 *     @pid_t long getpid();
 *
 *     // read(2) returns a signed long result, and its length parameter is an unsigned long
 *     @ssize_t long read(int fd, Pointer data, @size_t long len);
 *
 *
 * In addition, the following java types are mapped to a C pointer
 *
 * - String - equivalent to "const char *"
 * - Pointer - equivalent to "void *"
 * - Buffer - equivalent to "void *"
 */
public class VimY
{
    /* oops! */

    /*private*/ static cmdname_C[] cmdnames = new cmdname_C[]
    {
        new cmdname_C(u8("append"),        ex_append,
                                           BANG|RANGE|ZEROR|TRLBAR|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("abbreviate"),    ex_abbreviate,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("abclear"),       ex_abclear,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("aboveleft"),     ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("all"),           ex_all,
                                           BANG|RANGE|NOTADR|COUNT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("args"),          ex_args,
                                           BANG|FILES|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("argadd"),        ex_argadd,
                                           BANG|NEEDARG|RANGE|NOTADR|ZEROR|FILES|TRLBAR,
                                           ADDR_ARGUMENTS),
        new cmdname_C(u8("argdelete"),     ex_argdelete,
                                           BANG|RANGE|NOTADR|FILES|TRLBAR,
                                           ADDR_ARGUMENTS),
        new cmdname_C(u8("argdo"),         ex_listdo,
                                           BANG|NEEDARG|EXTRA|NOTRLCOM|RANGE|NOTADR|DFLALL,
                                           ADDR_ARGUMENTS),
        new cmdname_C(u8("argedit"),       ex_argedit,
                                           BANG|NEEDARG|RANGE|NOTADR|ZEROR|FILE1|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_ARGUMENTS),
        new cmdname_C(u8("argglobal"),     ex_args,
                                           BANG|FILES|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("arglocal"),      ex_args,
                                           BANG|FILES|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("argument"),      ex_argument,
                                           BANG|RANGE|NOTADR|COUNT|EXTRA|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_ARGUMENTS),
        new cmdname_C(u8("ascii"),         ex_ascii,
                                           TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("autocmd"),       ex_autocmd,
                                           BANG|EXTRA|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("augroup"),       ex_autocmd,
                                           BANG|WORD1|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("buffer"),        ex_buffer,
                                           BANG|RANGE|NOTADR|BUFNAME|BUFUNL|COUNT|EXTRA|EDITCMD|TRLBAR,
                                           ADDR_BUFFERS),
        new cmdname_C(u8("bNext"),         ex_bprevious,
                                           BANG|RANGE|NOTADR|COUNT|EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("ball"),          ex_buffer_all,
                                           RANGE|NOTADR|COUNT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("badd"),          ex_edit,
                                           NEEDARG|FILE1|EDITCMD|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("bdelete"),       ex_bunload,
                                           BANG|RANGE|NOTADR|BUFNAME|COUNT|EXTRA|TRLBAR,
                                           ADDR_BUFFERS),
        new cmdname_C(u8("belowright"),    ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("bfirst"),        ex_brewind,
                                           BANG|RANGE|NOTADR|EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("blast"),         ex_blast,
                                           BANG|RANGE|NOTADR|EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("bmodified"),     ex_bmodified,
                                           BANG|RANGE|NOTADR|COUNT|EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("bnext"),         ex_bnext,
                                           BANG|RANGE|NOTADR|COUNT|EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("botright"),      ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("bprevious"),     ex_bprevious,
                                           BANG|RANGE|NOTADR|COUNT|EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("brewind"),       ex_brewind,
                                           BANG|RANGE|NOTADR|EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("break"),         ex_break,
                                           TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("breakadd"),      ex_breakadd,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("breakdel"),      ex_breakdel,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("breaklist"),     ex_breaklist,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("browse"),        ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("buffers"),       ex_buflist,
                                           BANG|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("bufdo"),         ex_listdo,
                                           BANG|NEEDARG|EXTRA|NOTRLCOM|RANGE|NOTADR|DFLALL,
                                           ADDR_BUFFERS),
        new cmdname_C(u8("bunload"),       ex_bunload,
                                           BANG|RANGE|NOTADR|BUFNAME|COUNT|EXTRA|TRLBAR,
                                           ADDR_LOADED_BUFFERS),
        new cmdname_C(u8("bwipeout"),      ex_bunload,
                                           BANG|RANGE|NOTADR|BUFNAME|BUFUNL|COUNT|EXTRA|TRLBAR,
                                           ADDR_BUFFERS),
        new cmdname_C(u8("change"),        ex_change,
                                           BANG|RANGE|COUNT|TRLBAR|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("cabbrev"),       ex_abbreviate,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("cabclear"),      ex_abclear,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("call"),          ex_call,
                                           RANGE|NEEDARG|EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("catch"),         ex_catch,
                                           EXTRA|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("center"),        ex_align,
                                           TRLBAR|RANGE|EXTRA|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("changes"),       ex_changes,
                                           TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("checktime"),     ex_checktime,
                                           RANGE|NOTADR|BUFNAME|COUNT|EXTRA|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("close"),         ex_close,
                                           BANG|RANGE|NOTADR|COUNT|TRLBAR|CMDWIN,
                                           ADDR_WINDOWS),
        new cmdname_C(u8("cmap"),          ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("cmapclear"),     ex_mapclear,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("cnoremap"),      ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("cnoreabbrev"),   ex_abbreviate,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("copy"),          ex_copymove,
                                           RANGE|EXTRA|TRLBAR|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("colorscheme"),   ex_colorscheme,
                                           WORD1|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("command"),       ex_command,
                                           EXTRA|BANG|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("comclear"),      ex_comclear,
                                           TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("continue"),      ex_continue,
                                           TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("confirm"),       ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("cquit"),         ex_cquit,
                                           TRLBAR|BANG,
                                           ADDR_LINES),
        new cmdname_C(u8("cunmap"),        ex_unmap,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("cunabbrev"),     ex_abbreviate,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("delete"),        ex_operators,
                                           RANGE|REGSTR|COUNT|TRLBAR|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("delmarks"),      ex_delmarks,
                                           BANG|EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("debug"),         ex_debug,
                                           NEEDARG|EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("debuggreedy"),   ex_debuggreedy,
                                           RANGE|NOTADR|ZEROR|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("delcommand"),    ex_delcommand,
                                           NEEDARG|WORD1|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("delfunction"),   ex_delfunction,
                                           NEEDARG|WORD1|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("display"),       ex_display,
                                           EXTRA|NOTRLCOM|TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("digraphs"),      ex_digraphs,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("doautocmd"),     ex_doautocmd,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("doautoall"),     ex_doautoall,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("edit"),          ex_edit,
                                           BANG|FILE1|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("earlier"),       ex_later,
                                           TRLBAR|EXTRA|NOSPC|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("echo"),          ex_echo,
                                           EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("echoerr"),       ex_execute,
                                           EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("echohl"),        ex_echohl,
                                           EXTRA|TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("echomsg"),       ex_execute,
                                           EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("echon"),         ex_echo,
                                           EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("else"),          ex_else,
                                           TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("elseif"),        ex_else,
                                           EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("endif"),         ex_endif,
                                           TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("endfunction"),   ex_endfunction,
                                           TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("endfor"),        ex_endwhile,
                                           TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("endtry"),        ex_endtry,
                                           TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("endwhile"),      ex_endwhile,
                                           TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("enew"),          ex_edit,
                                           BANG|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("ex"),            ex_edit,
                                           BANG|FILE1|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("execute"),       ex_execute,
                                           EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("exit"),          ex_exit,
                                           RANGE|BANG|FILE1|ARGOPT|DFLALL|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("files"),         ex_buflist,
                                           BANG|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("finally"),       ex_finally,
                                           TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("finish"),        ex_finish,
                                           TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("first"),         ex_rewind,
                                           EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("fixdel"),        ex_fixdel,
                                           TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("for"),           ex_while,
                                           EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("function"),      ex_function,
                                           EXTRA|BANG|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("global"),        ex_global,
                                           RANGE|BANG|EXTRA|DFLALL|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("goto"),          ex_goto,
                                           RANGE|NOTADR|COUNT|TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("highlight"),     ex_highlight,
                                           BANG|EXTRA|TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("hide"),          ex_hide,
                                           BANG|RANGE|NOTADR|COUNT|EXTRA|NOTRLCOM,
                                           ADDR_WINDOWS),
        new cmdname_C(u8("history"),       ex_history,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("insert"),        ex_append,
                                           BANG|RANGE|TRLBAR|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("iabbrev"),       ex_abbreviate,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("iabclear"),      ex_abclear,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("if"),            ex_if,
                                           EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("imap"),          ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("imapclear"),     ex_mapclear,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("inoremap"),      ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("inoreabbrev"),   ex_abbreviate,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("iunmap"),        ex_unmap,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("iunabbrev"),     ex_abbreviate,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("join"),          ex_join,
                                           BANG|RANGE|COUNT|EXFLAGS|TRLBAR|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("jumps"),         ex_jumps,
                                           TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("k"),             ex_mark,
                                           RANGE|WORD1|TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("keepmarks"),     ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("keepjumps"),     ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("keeppatterns"),  ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("keepalt"),       ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("list"),          ex_print,
                                           RANGE|COUNT|EXFLAGS|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("last"),          ex_last,
                                           EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("later"),         ex_later,
                                           TRLBAR|EXTRA|NOSPC|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("left"),          ex_align,
                                           TRLBAR|RANGE|EXTRA|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("leftabove"),     ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("let"),           ex_let,
                                           EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("lmap"),          ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("lmapclear"),     ex_mapclear,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("lnoremap"),      ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("lockmarks"),     ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("lockvar"),       ex_lockvar,
                                           BANG|EXTRA|NEEDARG|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("lunmap"),        ex_unmap,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("ls"),            ex_buflist,
                                           BANG|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("move"),          ex_copymove,
                                           RANGE|EXTRA|TRLBAR|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("mark"),          ex_mark,
                                           RANGE|WORD1|TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("map"),           ex_map,
                                           BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("mapclear"),      ex_mapclear,
                                           EXTRA|BANG|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("marks"),         ex_marks,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("match"),         ex_match,
                                           RANGE|NOTADR|EXTRA|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("messages"),      ex_messages,
                                           TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("mode"),          ex_mode,
                                           WORD1|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("next"),          ex_next,
                                           RANGE|NOTADR|BANG|FILES|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("new"),           ex_splitview,
                                           BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("nmap"),          ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("nmapclear"),     ex_mapclear,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("nnoremap"),      ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("noremap"),       ex_map,
                                           BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("noautocmd"),     ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("nohlsearch"),    ex_nohlsearch,
                                           TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("noreabbrev"),    ex_abbreviate,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("normal"),        ex_normal,
                                           RANGE|BANG|EXTRA|NEEDARG|NOTRLCOM|USECTRLV|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("number"),        ex_print,
                                           RANGE|COUNT|EXFLAGS|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("nunmap"),        ex_unmap,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("open"),          ex_open,
                                           RANGE|BANG|EXTRA,
                                           ADDR_LINES),
        new cmdname_C(u8("omap"),          ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("omapclear"),     ex_mapclear,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("only"),          ex_only,
                                           BANG|NOTADR|RANGE|COUNT|TRLBAR,
                                           ADDR_WINDOWS),
        new cmdname_C(u8("onoremap"),      ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("ounmap"),        ex_unmap,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("ownsyntax"),     ex_ownsyntax,
                                           EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("print"),         ex_print,
                                           RANGE|COUNT|EXFLAGS|TRLBAR|CMDWIN|SBOXOK,
                                           ADDR_LINES),
        new cmdname_C(u8("previous"),      ex_previous,
                                           EXTRA|RANGE|NOTADR|COUNT|BANG|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("profdel"),       ex_breakdel,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("put"),           ex_put,
                                           RANGE|BANG|REGSTR|TRLBAR|ZEROR|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("quit"),          ex_quit,
                                           BANG|RANGE|COUNT|NOTADR|TRLBAR|CMDWIN,
                                           ADDR_WINDOWS),
        new cmdname_C(u8("quitall"),       ex_quit_all,
                                           BANG|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("qall"),          ex_quit_all,
                                           BANG|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("read"),          ex_read,
                                           BANG|RANGE|FILE1|ARGOPT|TRLBAR|ZEROR|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("redo"),          ex_redo,
                                           TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("redir"),         ex_redir,
                                           BANG|FILES|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("redraw"),        ex_redraw,
                                           BANG|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("redrawstatus"),  ex_redrawstatus,
                                           BANG|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("registers"),     ex_display,
                                           EXTRA|NOTRLCOM|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("resize"),        ex_resize,
                                           RANGE|NOTADR|TRLBAR|WORD1,
                                           ADDR_LINES),
        new cmdname_C(u8("retab"),         ex_retab,
                                           TRLBAR|RANGE|DFLALL|BANG|WORD1|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("return"),        ex_return,
                                           EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("rewind"),        ex_rewind,
                                           EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("right"),         ex_align,
                                           TRLBAR|RANGE|EXTRA|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("rightbelow"),    ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("runtime"),       ex_runtime,
                                           BANG|NEEDARG|FILES|TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("rundo"),         ex_rundo,
                                           NEEDARG|FILE1,
                                           ADDR_LINES),
        new cmdname_C(u8("substitute"),    ex_sub,
                                           RANGE|EXTRA|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("sNext"),         ex_previous,
                                           EXTRA|RANGE|NOTADR|COUNT|BANG|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("sargument"),     ex_argument,
                                           BANG|RANGE|NOTADR|COUNT|EXTRA|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_ARGUMENTS),
        new cmdname_C(u8("sall"),          ex_all,
                                           BANG|RANGE|NOTADR|COUNT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("sandbox"),       ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("saveas"),        ex_write,
                                           BANG|DFLALL|FILE1|ARGOPT|CMDWIN|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("sbuffer"),       ex_buffer,
                                           BANG|RANGE|NOTADR|BUFNAME|BUFUNL|COUNT|EXTRA|EDITCMD|TRLBAR,
                                           ADDR_BUFFERS),
        new cmdname_C(u8("sbNext"),        ex_bprevious,
                                           RANGE|NOTADR|COUNT|EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("sball"),         ex_buffer_all,
                                           RANGE|NOTADR|COUNT|EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("sbfirst"),       ex_brewind,
                                           EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("sblast"),        ex_blast,
                                           EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("sbmodified"),    ex_bmodified,
                                           RANGE|NOTADR|COUNT|EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("sbnext"),        ex_bnext,
                                           RANGE|NOTADR|COUNT|EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("sbprevious"),    ex_bprevious,
                                           RANGE|NOTADR|COUNT|EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("sbrewind"),      ex_brewind,
                                           EDITCMD|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("scriptnames"),   ex_scriptnames,
                                           TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("set"),           ex_set,
                                           TRLBAR|EXTRA|CMDWIN|SBOXOK,
                                           ADDR_LINES),
        new cmdname_C(u8("setfiletype"),   ex_setfiletype,
                                           TRLBAR|EXTRA|NEEDARG|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("setglobal"),     ex_set,
                                           TRLBAR|EXTRA|CMDWIN|SBOXOK,
                                           ADDR_LINES),
        new cmdname_C(u8("setlocal"),      ex_set,
                                           TRLBAR|EXTRA|CMDWIN|SBOXOK,
                                           ADDR_LINES),
        new cmdname_C(u8("sfirst"),        ex_rewind,
                                           EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("silent"),        ex_wrongmodifier,
                                           NEEDARG|EXTRA|BANG|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("sleep"),         ex_sleep,
                                           RANGE|NOTADR|COUNT|EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("slast"),         ex_last,
                                           EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("smagic"),        ex_submagic,
                                           RANGE|EXTRA|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("smap"),          ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("smapclear"),     ex_mapclear,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("snext"),         ex_next,
                                           RANGE|NOTADR|BANG|FILES|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("snomagic"),      ex_submagic,
                                           RANGE|EXTRA|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("snoremap"),      ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("source"),        ex_source,
                                           BANG|FILE1|TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("sort"),          ex_sort,
                                           RANGE|DFLALL|BANG|EXTRA|NOTRLCOM|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("split"),         ex_splitview,
                                           BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("sprevious"),     ex_previous,
                                           EXTRA|RANGE|NOTADR|COUNT|BANG|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("srewind"),       ex_rewind,
                                           EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("stop"),          ex_stop,
                                           TRLBAR|BANG|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("startinsert"),   ex_startinsert,
                                           BANG|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("startgreplace"), ex_startinsert,
                                           BANG|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("startreplace"),  ex_startinsert,
                                           BANG|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("stopinsert"),    ex_stopinsert,
                                           BANG|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("sunhide"),       ex_buffer_all,
                                           RANGE|NOTADR|COUNT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("sunmap"),        ex_unmap,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("suspend"),       ex_stop,
                                           TRLBAR|BANG|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("sview"),         ex_splitview,
                                           BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("syntax"),        ex_syntax,
                                           EXTRA|NOTRLCOM|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("syncbind"),      ex_syncbind,
                                           TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("t"),             ex_copymove,
                                           RANGE|EXTRA|TRLBAR|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("tab"),           ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("tabclose"),      ex_tabclose,
                                           RANGE|NOTADR|COUNT|BANG|TRLBAR|CMDWIN,
                                           ADDR_TABS),
        new cmdname_C(u8("tabdo"),         ex_listdo,
                                           NEEDARG|EXTRA|NOTRLCOM|RANGE|NOTADR|DFLALL,
                                           ADDR_TABS),
        new cmdname_C(u8("tabedit"),       ex_splitview,
                                           BANG|FILE1|RANGE|NOTADR|ZEROR|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_TABS),
        new cmdname_C(u8("tabfirst"),      ex_tabnext,
                                           TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("tabmove"),       ex_tabmove,
                                           RANGE|NOTADR|ZEROR|EXTRA|NOSPC|TRLBAR,
                                           ADDR_TABS),
        new cmdname_C(u8("tablast"),       ex_tabnext,
                                           TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("tabnext"),       ex_tabnext,
                                           RANGE|NOTADR|COUNT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("tabnew"),        ex_splitview,
                                           BANG|FILE1|RANGE|NOTADR|ZEROR|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_TABS),
        new cmdname_C(u8("tabonly"),       ex_tabonly,
                                           BANG|RANGE|NOTADR|TRLBAR|CMDWIN,
                                           ADDR_TABS),
        new cmdname_C(u8("tabprevious"),   ex_tabnext,
                                           RANGE|NOTADR|COUNT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("tabNext"),       ex_tabnext,
                                           RANGE|NOTADR|COUNT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("tabrewind"),     ex_tabnext,
                                           TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("tabs"),          ex_tabs,
                                           TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("throw"),         ex_throw,
                                           EXTRA|NEEDARG|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("topleft"),       ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("try"),           ex_try,
                                           TRLBAR|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("undo"),          ex_undo,
                                           RANGE|NOTADR|COUNT|ZEROR|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("undojoin"),      ex_undojoin,
                                           TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("undolist"),      ex_undolist,
                                           TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("unabbreviate"),  ex_abbreviate,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("unhide"),        ex_buffer_all,
                                           RANGE|NOTADR|COUNT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("unlet"),         ex_unlet,
                                           BANG|EXTRA|NEEDARG|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("unlockvar"),     ex_lockvar,
                                           BANG|EXTRA|NEEDARG|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("unmap"),         ex_unmap,
                                           BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("unsilent"),      ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("update"),        ex_update,
                                           RANGE|BANG|FILE1|ARGOPT|DFLALL|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("vglobal"),       ex_global,
                                           RANGE|EXTRA|DFLALL|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("verbose"),       ex_wrongmodifier,
                                           NEEDARG|RANGE|NOTADR|EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("vertical"),      ex_wrongmodifier,
                                           NEEDARG|EXTRA|NOTRLCOM,
                                           ADDR_LINES),
        new cmdname_C(u8("visual"),        ex_edit,
                                           BANG|FILE1|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("view"),          ex_edit,
                                           BANG|FILE1|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("vmap"),          ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("vmapclear"),     ex_mapclear,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("vnoremap"),      ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("vnew"),          ex_splitview,
                                           BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("vsplit"),        ex_splitview,
                                           BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("vunmap"),        ex_unmap,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("write"),         ex_write,
                                           RANGE|BANG|FILE1|ARGOPT|DFLALL|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("wNext"),         ex_wnext,
                                           RANGE|NOTADR|BANG|FILE1|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("wall"),          ex_wqall,
                                           BANG|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("while"),         ex_while,
                                           EXTRA|NOTRLCOM|SBOXOK|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("winsize"),       ex_winsize,
                                           EXTRA|NEEDARG|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("wincmd"),        ex_wincmd,
                                           NEEDARG|WORD1|RANGE|NOTADR,
                                           ADDR_WINDOWS),
        new cmdname_C(u8("windo"),         ex_listdo,
                                           BANG|NEEDARG|EXTRA|NOTRLCOM|RANGE|NOTADR|DFLALL,
                                           ADDR_WINDOWS),
        new cmdname_C(u8("winpos"),        ex_winpos,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("wnext"),         ex_wnext,
                                           RANGE|NOTADR|BANG|FILE1|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("wprevious"),     ex_wnext,
                                           RANGE|NOTADR|BANG|FILE1|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("wq"),            ex_exit,
                                           RANGE|BANG|FILE1|ARGOPT|DFLALL|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("wqall"),         ex_wqall,
                                           BANG|FILE1|ARGOPT|DFLALL|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("wundo"),         ex_wundo,
                                           BANG|NEEDARG|FILE1,
                                           ADDR_LINES),
        new cmdname_C(u8("xit"),           ex_exit,
                                           RANGE|BANG|FILE1|ARGOPT|DFLALL|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("xall"),          ex_wqall,
                                           BANG|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("xmap"),          ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("xmapclear"),     ex_mapclear,
                                           EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("xnoremap"),      ex_map,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("xunmap"),        ex_unmap,
                                           EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("yank"),          ex_operators,
                                           RANGE|REGSTR|COUNT|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("z"),             ex_z,
                                           RANGE|EXTRA|EXFLAGS|TRLBAR|CMDWIN,
                                           ADDR_LINES),

        /* commands that don't start with a lowercase letter */

        new cmdname_C(u8("!"),             ex_bang,
                                           RANGE|BANG|FILES|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("#"),             ex_print,
                                           RANGE|COUNT|EXFLAGS|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("&"),             ex_sub,
                                           RANGE|EXTRA|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("*"),             ex_at,
                                           RANGE|EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("<"),             ex_operators,
                                           RANGE|COUNT|EXFLAGS|TRLBAR|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("="),             ex_equal,
                                           RANGE|TRLBAR|DFLALL|EXFLAGS|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8(">"),             ex_operators,
                                           RANGE|COUNT|EXFLAGS|TRLBAR|CMDWIN|MODIFY,
                                           ADDR_LINES),
        new cmdname_C(u8("@"),             ex_at,
                                           RANGE|EXTRA|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("Next"),          ex_previous,
                                           EXTRA|RANGE|NOTADR|COUNT|BANG|EDITCMD|ARGOPT|TRLBAR,
                                           ADDR_LINES),
        new cmdname_C(u8("Print"),         ex_print,
                                           RANGE|COUNT|EXFLAGS|TRLBAR|CMDWIN,
                                           ADDR_LINES),
        new cmdname_C(u8("~"),             ex_sub,
                                           RANGE|EXTRA|CMDWIN|MODIFY,
                                           ADDR_LINES),
    };

    /*private*/ static expgen_C[] expgen_tab = new expgen_C[]
    {
        new expgen_C(EXPAND_COMMANDS,       get_command_name,       false, true),
        new expgen_C(EXPAND_HISTORY,        get_history_arg,        true,  true),
        new expgen_C(EXPAND_USER_COMMANDS,  get_user_commands,      false, true),
        new expgen_C(EXPAND_USER_ADDR_TYPE, get_user_cmd_addr_type, false, true),
        new expgen_C(EXPAND_USER_CMD_FLAGS, get_user_cmd_flags,     false, true),
        new expgen_C(EXPAND_USER_NARGS,     get_user_cmd_nargs,     false, true),
        new expgen_C(EXPAND_USER_COMPLETE,  get_user_cmd_complete,  false, true),
        new expgen_C(EXPAND_USER_VARS,      get_user_var_name,      false, true),
        new expgen_C(EXPAND_FUNCTIONS,      get_function_name,      false, true),
        new expgen_C(EXPAND_USER_FUNC,      get_user_func_name,     false, true),
        new expgen_C(EXPAND_EXPRESSION,     get_expr_name,          false, true),
        new expgen_C(EXPAND_SYNTAX,         get_syntax_name,        true,  true),
        new expgen_C(EXPAND_HIGHLIGHT,      get_highlight_name,     true,  true),
        new expgen_C(EXPAND_EVENTS,         get_event_name,         true,  true),
        new expgen_C(EXPAND_AUGROUP,        get_augroup_name,       true,  true),
    };
}
